name: axe DevHub
description: Get the axe DevHub status for a commit

inputs:
  api_key:
    description: axe DevHub API Key
    required: true
  server_url:
    description: axe server URL
    required: false
    default: https://axe.deque.com
  retry_count:
    description: number of times to attempt fetching the commit status
    required: false
    default: 10
  github_token:
    description: GitHub token
    default: ${{ github.token }}
    required: true

outputs:
  project:
    description: Project name
    value: ${{ steps.main.outputs.project }}
  axe_url:
    description: Axe URL for the commit's issues
    value: ${{ steps.main.outputs.axe_url }}
  issue_count:
    description: Number of violations found
    value: ${{ steps.main.outputs.issue_count }}

runs:
  using: composite
  steps:
    - uses: jwalton/gh-find-current-pr@v1
      id: find_pr
    - id: main
      run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        API_KEY: ${{ inputs.api_key }}
        SERVER_URL: ${{ inputs.server_url }}
        RETRY_COUNT: ${{ inputs.retry_count }}
        COMMIT_SHA: ${{ github.sha }}
    # Add a comment reporting the number of violations.
    - if: ${{ failure() }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: axe-devhub
        message: |
          axe DevHub found **${{ steps.main.outputs.issue_count }}** accessibility violations in this PR.

          See the full report on [axe DevHub](${{ steps.main.outputs.axe_url }}).
        GITHUB_TOKEN: ${{ inputs.github_token }}
        number: ${{ steps.find_pr.outputs.pr }}
    # Hide a previously added comment if there are no violations.
    - if: ${{ success() }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: axe-devhub
        hide: true
        hide_classify: OUTDATED
        GITHUB_TOKEN: ${{ inputs.github_token }}
        number: ${{ steps.find_pr.outputs.pr }}
